# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Justin Cheung
email: JS421503@dal.ca
description: > # this means to ignore newlines until "baseurl:"
  Hi. I'm a 4th year Computer Science student currently studying at Dalhousie University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  muffinlightning

# Build settings
markdown: kramdown
